In [1]:
import pandas as pd

In [5]:
# from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
# from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.tree import export_graphviz
from sklearn.externals.six import StringIO 
from IPython.display import Image 
from pydot import graph_from_dot_data
import pandas as pd
import numpy as np

C:\Program Files\Python37\lib\site-packages\sklearn\externals\six.py:31: DeprecationWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", DeprecationWarning)

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
dataset= pd.read_csv("poker-hand-testing.data")

In [8]:
dataset.head()

   S1  C1  S2  C2  S3  C3  S4  C4  S5  C5  CLASS
0   1   1   1  13   2   4   2   3   1  12      0
1   3  12   3   2   3  11   4   5   2   5      1
2   1   9   4   6   1   4   3   2   3   9      1
3   1   4   3  13   2  13   2   1   3   6      1
4   3  10   2   7   1   2   2  11   4   9      0

In [12]:
x= dataset.iloc[:, 0:10]
y=dataset.iloc[:,-1]
# y=dataset.select_dtypes(include=[object])

In [13]:
 ys=["0","1","2","3","4","5","7","8","9","10"]

In [32]:
s=pd.DataFrame(y,columns =['CLASS'])

In [33]:
s['CLASS'].value_counts()

0    501209
1    422498
2     47622
3     21121
4      3885
5      1996
6      1424
7       230
8        12
9         3
Name: CLASS, dtype: int64

In [34]:
x

        S1  C1  S2  C2  S3  C3  S4  C4  S5  C5
0        1   1   1  13   2   4   2   3   1  12
1        3  12   3   2   3  11   4   5   2   5
2        1   9   4   6   1   4   3   2   3   9
3        1   4   3  13   2  13   2   1   3   6
4        3  10   2   7   1   2   2  11   4   9
5        1   3   4   5   3   4   1  12   4   6
6        2   6   4  11   2   3   4   9   1   7
7        3   2   4   9   3   7   4   3   4   5
8        4   4   3  13   1   8   3   9   3  10
9        1   9   3   8   4   4   1   7   3   5
10       4   7   3  12   1  13   1   9   2   6
11       2  12   1   3   2  11   2   7   4   8
12       4   2   2   9   2   7   1   5   3  11
13       1  13   2   6   1   6   2  11   3   5
14       3   8   2   7   1   9   3   6   2   3
15       2  10   1  11   1   9   3   1   1  13
16       4   2   4  12   2  12   2   7   3  10
17       4   5   2   2   4   9   1   5   4   1
18       2   3   3   9   2   1   2   6   4  10
19       1   7   2  11   4   1   2   9   3  13
20       4  12   1   6   3   1   2   2   1   8
21       2   5   3   1   3  13   4  13   3   8
22       1   3   4   8   2   1   1  12   3   5
23       2   8   4   6   1  12   2  13   1   8
24       1   7   4  13   4   9   1   9   1  10
25       2  13   3   3   2  11   2   6   1   4
26       4   3   2   4   4   9   2   8   1  11
27       2   5   3   7   2  12   3   3   2  11
28       3   4   2   1   3  10   1   8   4   1
29       4  11   2  13   4   4   3   8   4   1
...     ..  ..  ..  ..  ..  ..  ..  ..  ..  ..
999970   3   8   3  13   3   3   2   7   1  10
999971   4   2   1  12   2  12   4  11   2   9
999972   4   3   2   4   2   8   1   6   4  11
999973   3   7   4   9   3   6   3  12   2  11
999974   2   6   4   3   2   1   1   7   1  12
999975   4   3   2   7   3  10   1  12   4   1
999976   2   8   2  11   1   6   2   7   4  11
999977   3  13   2   3   1   4   2   1   3   1
999978   3   1   2   8   1   4   4  10   3   3
999979   3   3   2  12   4   2   3  13   1   9
999980   2  10   3  10   2   9   3  11   4  13
999981   3   5   1   2   2   1   2   9   2   8
999982   1   1   3   1   1  11   2   3   2   6
999983   2   5   4   7   1  11   4   6   3   5
999984   4   6   4   3   1   4   2   7   1   2
999985   1  11   1  13   2   6   3   6   2   1
999986   2   8   4  10   3   6   2   4   3   3
999987   1   8   4   9   3   1   1   1   2   8
999988   4   3   4   7   3   6   4  12   1   1
999989   1  11   3  13   2  13   4   3   3  10
999990   2  12   4   3   1   3   3   5   3   2
999991   1   4   4   8   4   5   3   9   2   1
999992   1   9   3   6   2   8   3   5   2   9
999993   1  12   3   9   3   6   1   3   1   9
999994   3   7   1   6   4  12   2   1   1   4
999995   3   1   1  12   2   9   4   9   2   6
999996   3   3   4   5   2   7   1   4   4   3
999997   1  11   4   7   3   9   1  13   2   7
999998   3  11   1   8   1   1   3  13   2   8
999999   2   5   2   9   4   9   2   3   3   3

[1000000 rows x 10 columns]

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y,random_state=1)

In [36]:
# from sklearn.preprocessing import StandardScaler
# scaler = StandardScaler()
# scaler.fit(X_train)

# X_train = scaler.transform(X_train)
# X_test = scaler.transform(X_test)

In [15]:
dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [16]:
dot_data = StringIO()
export_graphviz(dt, out_file=dot_data, feature_names=ys)
(graph, ) = graph_from_dot_data(dot_data.getvalue())
Image(graph.create_png())

NameError: name 'iris' is not defined

In [19]:
y_pred = dt.predict(X_test)

In [37]:
# from sklearn.neural_network import MLPClassifier
# mlp = MLPClassifier(hidden_layer_sizes=(10, 10, 10), max_iter=1000)
# mlp.fit(X_train, y_train.values.ravel())

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(10, 10, 10), learning_rate='constant',
              learning_rate_init=0.001, max_iter=1000, momentum=0.9,
              n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
              random_state=None, shuffle=True, solver='adam', tol=0.0001,
              validation_fraction=0.1, verbose=False, warm_start=False)

In [38]:
predictions = mlp.predict(X_test)

In [39]:
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import cross_val_score

print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))
# print

[[95297  4631     0     0     0     0     0     0     0]
 [39372 45159    94   137     0     0     0     0     0]
 [ 1613  7254   458   165     0     0     0     0     0]
 [  261  2964   272   763     0     0     0     1     0]
 [  286   550     0     0     0     0     0     0     0]
 [  372    12     0     0     0     0     0     0     0]
 [    0   156    53    74     0     0     0     2     0]
 [    0     8    10    25     0     0     3     5     0]
 [    1     2     0     0     0     0     0     0     0]]
C:\Program Files\Python37\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
              precision    recall  f1-score   support

           0       0.69      0.95      0.80     99928
           1       0.74      0.53      0.62     84762
           2       0.52      0.05      0.09      9490
           3       0.66      0.18      0.28      4261
           4       0.00      0.00      0.00       836
           5       0.00      0.00      0.00       384
           6       0.00      0.00      0.00       285
           7       0.62      0.10      0.17        51
           8       0.00      0.00      0.00         3

    accuracy                           0.71    200000
   macro avg       0.36      0.20      0.22    200000
weighted avg       0.70      0.71      0.67    200000